import Navbar from "./navbar";
import Footer from "./Footer";
import Head from "next/head";
import styles from "../components/Layout.module.scss";

export default function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty Wiki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main>{children}</main>
      <Footer />
    </div>
  );
}
